name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  cicd:
    uses: ./.github/workflows/cicd.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::311141562939:role/GithubActions-EncurtadorLinks-Role"
      aws-region: "us-east-2"
      aws-statefile-s3-bucket: "terraform-311141562939-statefile"
      aws-lock-dynamodb-table: "311141562939-terraform-lock"